# SPDX-License-Identifier: GPL-2.0
#
# Makefile for nfc devices
#

# add by huawei
obj-y += nfc_interface.o
obj-y += nfc_kernel_common/
obj-$(CONFIG_NFC_PN547)		+= pn547/
obj-$(CONFIG_NFC_ST21NFC)   += st21nfc/
obj-$(CONFIG_NFC_THN31) += thn31/
